version: "3.8"
services:
  app:
    build:
      context: .
      target: production
    image: todo-app:production
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      DATABASE_URL: $DATABASE_URL
